# Zeon - Pure Rust Operating System
# https://github.com/DDDDprog/zeon-kernel

[toolchain]
channel = "nightly"
components = [ "rust-src", "rustfmt", "rust-analyzer" ]
targets = ["aarch64-unknown-none-softfloat", "aarch64-unknown-linux-musl"]
