# Zeon - Pure Rust Operating System
# https://github.com/DDDDprog/zeon-kernel

# Zeon - Zeon
[build]
target = "aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
runner = "scripts/qemu_runner.py"
